version: "3.8"
services:
    rest_api:
        build: .
        env_file:
            - ./env/mysql.env
        ports:
            - "8080:8080"
        volumes:
            - images:/app/images
            - logs:/app/ServicesLayer/logs
            # - .:/app
            # - /app/main
    black_list_redis:
        build: #redis en dockerhub
        ports:
            - "6379:6379"
        volumes:
            #- blacklist:/app/
    #   depends_on: 
    #         - mailing_service
    # # mailing_service:
volumes:
    images:
    logs:
