version: "3.8"
services:
    rest_api:
        build: .
        env_file:
            - ./env/mysql.env
        ports:
            - "8080:8080"
        volumes:
            - images:/app/images
            - logs:/app/ServicesLayer/logs
        depends_on: 
            - mailing_service
            - black_list_redis
            - cache_redis
    black_list_redis:
        image: "redis"
        ports:
            - "6379:6379"
        volumes:
            - blacklist:/data
        entrypoint: redis-server --appendonly yes
    cache_redis:
        image: "redis"
        ports:
            - "8250:6379"
        volumes:
            - cache_redis:/data
        entrypoint: redis-server --appendonly yes
    mailing_service:
        image: "edhv99/node-grpc-server:latest"
        ports:
            - "4500:4500"
volumes:
    images:
    logs:
    blacklist:
    cache_redis:
