name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
  

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Image
      run: docker build . --tag on_the_way_rest_api:$(date +%s)      
    
    - name: Publish to registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: adairhz/on_the_way_restapi
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
